apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: maria-connector
  namespace: kafka
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    # 토픽 프리픽스
    topic.prefix: binance_topic
    # MariaDB 설정
    database.hostname: "10.0.10.214"
    database.port: "3306"
    database.user: "binance_user"
    database.password: "password"
    database.server.id: "184054"  # 고유한 서버 ID
    database.server.name: "my-mariadb-db"  # 서버 이름
    database.whitelist: "binance_data"  # 감시할 데이터베이스
    table.include.list: "binance_data.trades"  # 테이블 포함 형식 변경
    
    # Kafka 설정
    schema.history.internal.kafka.bootstrap.servers: "my-cluster-kafka-bootstrap.kafka.svc:9092"
    schema.history.internal.kafka.topic: "schema-changes.inventory"
    database.history.kafka.bootstrap.servers: "my-cluster-kafka-bootstrap.kafka.svc:9092"
    database.history.kafka.topic: "database-changes.inventory"

    # 기타 설정
    include.schema.changes: "true"
    database.history.kafka.reset.offset: "true"

